server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upball?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: upball
    password: upball123

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.upball: debug
    com.baomidou.mybatisplus: debug
